// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqV2ZCKHQZI0X1gds04AYlxN4Xo8pbe5I',
    appId: '1:556053775232:web:7104ad1b35a63b8923f765',
    messagingSenderId: '556053775232',
    projectId: 'hearable-94cfb',
    authDomain: 'hearable-94cfb.firebaseapp.com',
    storageBucket: 'hearable-94cfb.firebasestorage.app',
    measurementId: 'G-CB4HNVZKJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjvCdjhBF-j0bNUvyZW9uIe1AN26B-pY',
    appId: '1:556053775232:android:ceae0c07a9635d9123f765',
    messagingSenderId: '556053775232',
    projectId: 'hearable-94cfb',
    storageBucket: 'hearable-94cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9PT8k75ukgPX3997ZPG3HNy0IFgxkQc',
    appId: '1:556053775232:ios:0c05b3f733aa6af323f765',
    messagingSenderId: '556053775232',
    projectId: 'hearable-94cfb',
    storageBucket: 'hearable-94cfb.firebasestorage.app',
    iosBundleId: 'com.example.hearable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF9PT8k75ukgPX3997ZPG3HNy0IFgxkQc',
    appId: '1:556053775232:ios:0c05b3f733aa6af323f765',
    messagingSenderId: '556053775232',
    projectId: 'hearable-94cfb',
    storageBucket: 'hearable-94cfb.firebasestorage.app',
    iosBundleId: 'com.example.hearable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqV2ZCKHQZI0X1gds04AYlxN4Xo8pbe5I',
    appId: '1:556053775232:web:b8b92111fc825a1223f765',
    messagingSenderId: '556053775232',
    projectId: 'hearable-94cfb',
    authDomain: 'hearable-94cfb.firebaseapp.com',
    storageBucket: 'hearable-94cfb.firebasestorage.app',
    measurementId: 'G-Y709MZVZJ8',
  );
}
